-- ============================================================================
-- CRM for TP — migration: Ежедневный отчёт ТП («Работа за сегодня»)
-- ============================================================================
-- Назначение: добавить таблицы для вкладки «Ежедневный отчёт», где каждый
-- торговый представитель в конце рабочего дня отвечает на вопросы админа.
--
-- Причина фичи: часть выплат врачам теперь безналичная, ТП больше не проводят
-- весь день в разъездах по больницам — админу нужен структурированный дневной
-- отчёт «что сделал сотрудник за день».
--
-- Принципы (в стиле проекта, см. sql-sales-plan-payments.sql):
--   * Все объекты создаются идемпотентно (IF NOT EXISTS / ON CONFLICT).
--   * Frontend читает/пишет через anon-ключ, логин хранится в строках
--     (rep_login), поэтому RLS даёт anon-роли полный доступ, чтобы не сломать
--     текущую (пока небезопасную) модель. Строгий вариант политик — в конце.
--   * updated_at обслуживается общим триггером set_updated_at().
--
-- ВАЖНО: этот файл НЕ применяется автоматически. Запускать вручную в Supabase
-- SQL Editor. Никаких секретов (service_role) здесь нет и быть не должно.
-- ============================================================================

-- Общий триггер обновления updated_at (создаётся в других миграциях; дублируем
-- идемпотентно, чтобы файл можно было запускать автономно).
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;


-- ===========================================================================
-- 1. crm_daily_report_questions — вопросы отчёта
-- ===========================================================================
-- Один справочник и для глобальных вопросов (applies_to='all'), и для
-- персональных вопросов конкретного ТП (applies_to=<rep_login>).
--   * subquestions — массив строк-подсказок (подвопросы) внутри вопроса;
--   * is_active=FALSE — «мягкое удаление» (вопрос скрыт, но история ответов
--     на него сохраняется);
--   * sort_order — порядок вопросов (по возрастанию).
CREATE TABLE IF NOT EXISTS crm_daily_report_questions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_text TEXT NOT NULL,
    subquestions  JSONB NOT NULL DEFAULT '[]'::jsonb,  -- массив строк-подсказок
    is_active     BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order    INTEGER NOT NULL DEFAULT 0,
    applies_to    TEXT NOT NULL DEFAULT 'all',          -- 'all' | <rep_login>
    created_by    TEXT,                                 -- логин админа-автора
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_crm_dr_questions_applies ON crm_daily_report_questions (applies_to);
CREATE INDEX IF NOT EXISTS idx_crm_dr_questions_active  ON crm_daily_report_questions (is_active);
CREATE INDEX IF NOT EXISTS idx_crm_dr_questions_order   ON crm_daily_report_questions (sort_order);

DROP TRIGGER IF EXISTS trg_crm_dr_questions_updated_at ON crm_daily_report_questions;
CREATE TRIGGER trg_crm_dr_questions_updated_at
    BEFORE UPDATE ON crm_daily_report_questions
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ===========================================================================
-- 2. crm_daily_report_question_overrides — персонализация глобальных вопросов
-- ===========================================================================
-- Позволяет для конкретного ТП: скрыть глобальный вопрос (is_hidden=TRUE)
-- и/или задать индивидуальный порядок (custom_sort_order). Одна строка на
-- пару (question_id, rep_login).
CREATE TABLE IF NOT EXISTS crm_daily_report_question_overrides (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_id       BIGINT NOT NULL REFERENCES crm_daily_report_questions (id) ON DELETE CASCADE,
    rep_login         TEXT NOT NULL,
    is_hidden         BOOLEAN NOT NULL DEFAULT FALSE,
    custom_sort_order INTEGER,                            -- NULL = порядок из вопроса
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_crm_dr_override UNIQUE (question_id, rep_login)
);

CREATE INDEX IF NOT EXISTS idx_crm_dr_overrides_rep ON crm_daily_report_question_overrides (rep_login);

DROP TRIGGER IF EXISTS trg_crm_dr_overrides_updated_at ON crm_daily_report_question_overrides;
CREATE TRIGGER trg_crm_dr_overrides_updated_at
    BEFORE UPDATE ON crm_daily_report_question_overrides
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ===========================================================================
-- 3. crm_daily_reports — «шапка» отчёта на пару (ТП, дата)
-- ===========================================================================
-- status: 'draft' (черновик, редактируется в течение дня) | 'submitted' (сдан).
CREATE TABLE IF NOT EXISTS crm_daily_reports (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rep_login    TEXT NOT NULL,
    report_date  DATE NOT NULL,
    status       TEXT NOT NULL DEFAULT 'draft',           -- 'draft' | 'submitted'
    submitted_at TIMESTAMPTZ,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_crm_daily_report UNIQUE (rep_login, report_date)
);

CREATE INDEX IF NOT EXISTS idx_crm_daily_reports_rep  ON crm_daily_reports (rep_login);
CREATE INDEX IF NOT EXISTS idx_crm_daily_reports_date ON crm_daily_reports (report_date);

DROP TRIGGER IF EXISTS trg_crm_daily_reports_updated_at ON crm_daily_reports;
CREATE TRIGGER trg_crm_daily_reports_updated_at
    BEFORE UPDATE ON crm_daily_reports
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ===========================================================================
-- 4. crm_daily_report_answers — ответы на вопросы в рамках отчёта
-- ===========================================================================
-- Одна строка на (report_id, question_id). Вопрос не удаляется физически при
-- деактивации, поэтому FK ON DELETE CASCADE только по отчёту; на вопрос —
-- RESTRICT (нельзя удалить вопрос, на который уже есть ответы — деактивируйте).
CREATE TABLE IF NOT EXISTS crm_daily_report_answers (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id   BIGINT NOT NULL REFERENCES crm_daily_reports (id) ON DELETE CASCADE,
    question_id BIGINT NOT NULL REFERENCES crm_daily_report_questions (id) ON DELETE RESTRICT,
    answer_text TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_crm_dr_answer UNIQUE (report_id, question_id)
);

CREATE INDEX IF NOT EXISTS idx_crm_dr_answers_report   ON crm_daily_report_answers (report_id);
CREATE INDEX IF NOT EXISTS idx_crm_dr_answers_question ON crm_daily_report_answers (question_id);

DROP TRIGGER IF EXISTS trg_crm_dr_answers_updated_at ON crm_daily_report_answers;
CREATE TRIGGER trg_crm_dr_answers_updated_at
    BEFORE UPDATE ON crm_daily_report_answers
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ===========================================================================
-- 5. Сид вопросов по умолчанию (глобальные, applies_to='all')
-- ===========================================================================
-- Идемпотентно: вставляем только если вопроса с таким текстом ещё нет.
-- Так повторный запуск миграции не создаёт дубликатов и не трогает уже
-- отредактированные админом вопросы.
INSERT INTO crm_daily_report_questions (question_text, subquestions, sort_order, applies_to, created_by)
SELECT v.question_text, v.subquestions::jsonb, v.sort_order, 'all', 'system'
FROM (VALUES
    ('Работа за сегодня: что сделала/сделал?',
     '["Кратко перечислите ключевые действия и результаты дня"]', 10),
    ('Кому позвонила/позвонил сегодня? Итог звонков?',
     '["ФИО/учреждение", "Тема разговора", "Итог и договорённости"]', 20),
    ('С какими врачами удалось улучшить взаимоотношения?',
     '["Что именно было сделано?", "Какие дальнейшие договорённости?"]', 30),
    ('Сколько новых врачей найдено?',
     '["ФИО", "Специальность", "Контакт", "Потенциал (низкий/средний/высокий)"]', 40),
    ('Какие врачи показывают потенциал, но продажи у них снизились?',
     '["Причина снижения (гипотеза)", "Что планируется сделать для роста продаж?"]', 50),
    ('Какой новый товар нужно привезти или протестировать?',
     '["Наименование", "Почему есть спрос / кто просил"]', 60),
    ('Проверены ли продажи 1C и DocSales за предыдущий день? Были ли расхождения?',
     '["Да/нет — проверено", "Были ли расхождения и на какую сумму?"]', 70),
    ('Если были расхождения — с какими продавцами говорили и почему возникла разница?',
     '["Продавец/точка", "Причина расхождения", "Как устранили/план"]', 80),
    ('Какие выплаты/долги врачам требуют внимания завтра?',
     '["Врач", "Сумма", "Срок / приоритет"]', 90),
    ('Какие задачи запланированы на завтра и какой ожидается результат?',
     '["Задача", "Ожидаемый результат"]', 100),
    ('Какие препятствия мешали работе сегодня и какая помощь нужна от админа?',
     '["Препятствие", "Какая помощь нужна"]', 110),
    ('Какие идеи по росту продаж/ассортимента/отношений появились сегодня?',
     '["Идея", "Ожидаемый эффект"]', 120)
) AS v(question_text, subquestions, sort_order)
WHERE NOT EXISTS (
    SELECT 1 FROM crm_daily_report_questions q
    WHERE q.applies_to = 'all' AND q.question_text = v.question_text
);


-- ===========================================================================
-- RLS / POLICIES (в стиле проекта: anon имеет полный доступ)
-- ===========================================================================
-- ВНИМАНИЕ: проект работает через anon-ключ без Supabase Auth. Чтобы не сломать
-- текущее поведение, включаем RLS и даём anon-роли полный доступ. Более строгий
-- вариант (ТП видит только свои отчёты) — в комментарии в конце файла; включать
-- после внедрения настоящей авторизации.
ALTER TABLE crm_daily_report_questions          ENABLE ROW LEVEL SECURITY;
ALTER TABLE crm_daily_report_question_overrides ENABLE ROW LEVEL SECURITY;
ALTER TABLE crm_daily_reports                   ENABLE ROW LEVEL SECURITY;
ALTER TABLE crm_daily_report_answers            ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='crm_daily_report_questions' AND policyname='dr_questions_all_anon') THEN
        CREATE POLICY dr_questions_all_anon ON crm_daily_report_questions FOR ALL USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='crm_daily_report_question_overrides' AND policyname='dr_overrides_all_anon') THEN
        CREATE POLICY dr_overrides_all_anon ON crm_daily_report_question_overrides FOR ALL USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='crm_daily_reports' AND policyname='dr_reports_all_anon') THEN
        CREATE POLICY dr_reports_all_anon ON crm_daily_reports FOR ALL USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='crm_daily_report_answers' AND policyname='dr_answers_all_anon') THEN
        CREATE POLICY dr_answers_all_anon ON crm_daily_report_answers FOR ALL USING (true) WITH CHECK (true);
    END IF;
END $$;

-- ---------------------------------------------------------------------------
-- Более строгий вариант (включить ПОСЛЕ внедрения Supabase Auth):
--   ТП видит и правит только свои отчёты, глобальные вопросы читают все,
--   изменяют только админы. Псевдокод — адаптировать под свою модель ролей:
--
-- DROP POLICY IF EXISTS dr_reports_all_anon ON crm_daily_reports;
-- CREATE POLICY dr_reports_own ON crm_daily_reports
--     FOR ALL USING (rep_login = auth.jwt() ->> 'login')
--     WITH CHECK (rep_login = auth.jwt() ->> 'login');
-- ---------------------------------------------------------------------------
