-- ============================================================================
-- CRM for TP — migration: расширенные профили врачей + специальности
-- ============================================================================
-- Назначение:
--   * добавить в crm_doctors поля для расширенного профиля врача,
--     заполняемые ВРУЧНУЮ из UI (описание, место работы, телефон, кошелёк,
--     рейтинги, заметки);
--   * добавить справочник специальностей crm_doctor_specialties + CRUD из UI;
--   * связать врача со специальностью (specialty_id) и сохранить текстовую
--     специальность (specialty) как запасной вариант.
--
-- Принципы:
--   * Все объекты создаются идемпотентно (ADD COLUMN IF NOT EXISTS / IF NOT EXISTS),
--     чтобы повторный запуск был безопасен.
--   * Новые поля НЕ перезаписываются backend-синхронизацией (scripts/sync-sales.js):
--     синк делает upsert по doctor_code и пишет только sync-поля
--     (doctor_name, discount_card_ref, discount_card_code, source,
--     discount_group, active, last_synced_at). Поля ниже в upsert не входят,
--     поэтому merge-duplicates их сохраняет — ручной ввод не теряется.
--   * RLS-политики "в стиле проекта": проект работает через anon-ключ,
--     поэтому anon разрешены чтение и запись (как у crm_doctors / crm_doctor_payments).
--
-- Применяется ПОСЛЕ sql-sales-plan-payments.sql (использует set_updated_at()
-- и существующую таблицу crm_doctors).
-- ============================================================================

-- ---------------------------------------------------------------------------
-- set_updated_at(): создаём, если миграция запускается отдельно от первой.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;


-- ===========================================================================
-- 1. crm_doctor_specialties — справочник специальностей / категорий врачей
-- ===========================================================================
-- Примеры: Ортопед, Кардиолог, Терапевт, Невролог, Педиатр ...
CREATE TABLE IF NOT EXISTS crm_doctor_specialties (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL UNIQUE,         -- название специальности
    icon        TEXT,                          -- эмодзи/иконка для чипа (опц.)
    color       TEXT,                          -- цвет чипа в HEX (опц.)
    sort_order  INTEGER DEFAULT 0,
    active       BOOLEAN DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_doctor_specialties_active ON crm_doctor_specialties (active);
CREATE INDEX IF NOT EXISTS idx_doctor_specialties_sort   ON crm_doctor_specialties (sort_order);

DROP TRIGGER IF EXISTS trg_doctor_specialties_updated_at ON crm_doctor_specialties;
CREATE TRIGGER trg_doctor_specialties_updated_at
    BEFORE UPDATE ON crm_doctor_specialties
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ===========================================================================
-- 2. crm_doctors — расширенный профиль врача (ручные поля)
-- ===========================================================================
-- ВАЖНО: эти колонки заполняются из UI и не входят в upsert синхронизации,
-- поэтому backend-синк их не затирает.
ALTER TABLE crm_doctors ADD COLUMN IF NOT EXISTS description          TEXT;
ALTER TABLE crm_doctors ADD COLUMN IF NOT EXISTS workplace            TEXT;
ALTER TABLE crm_doctors ADD COLUMN IF NOT EXISTS phone                TEXT;
ALTER TABLE crm_doctors ADD COLUMN IF NOT EXISTS wallet_number        TEXT;
ALTER TABLE crm_doctors ADD COLUMN IF NOT EXISTS specialty            TEXT;          -- текстовая специальность (запасной вариант)
ALTER TABLE crm_doctors ADD COLUMN IF NOT EXISTS specialty_id         BIGINT;        -- FK на crm_doctor_specialties
ALTER TABLE crm_doctors ADD COLUMN IF NOT EXISTS professional_rating  SMALLINT;      -- профессионализм 1..5
ALTER TABLE crm_doctors ADD COLUMN IF NOT EXISTS cooperation_rating   SMALLINT;      -- сотрудничество 1..5
ALTER TABLE crm_doctors ADD COLUMN IF NOT EXISTS notes                TEXT;

-- Ограничения рейтингов 1..5 (добавляем идемпотентно).
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_crm_doctors_prof_rating') THEN
        ALTER TABLE crm_doctors ADD CONSTRAINT chk_crm_doctors_prof_rating
            CHECK (professional_rating IS NULL OR professional_rating BETWEEN 1 AND 5);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_crm_doctors_coop_rating') THEN
        ALTER TABLE crm_doctors ADD CONSTRAINT chk_crm_doctors_coop_rating
            CHECK (cooperation_rating IS NULL OR cooperation_rating BETWEEN 1 AND 5);
    END IF;
    -- Связь врача со специальностью (ON DELETE SET NULL, чтобы удаление
    -- специальности не удаляло врача).
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_crm_doctors_specialty') THEN
        ALTER TABLE crm_doctors ADD CONSTRAINT fk_crm_doctors_specialty
            FOREIGN KEY (specialty_id) REFERENCES crm_doctor_specialties (id) ON DELETE SET NULL;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_crm_doctors_specialty_id ON crm_doctors (specialty_id);


-- ===========================================================================
-- 3. Стартовый набор специальностей (только если справочник пуст)
-- ===========================================================================
INSERT INTO crm_doctor_specialties (name, icon, sort_order)
SELECT v.name, v.icon, v.sort_order
FROM (VALUES
    ('Терапевт',   '🩺', 1),
    ('Кардиолог',  '❤️', 2),
    ('Невролог',   '🧠', 3),
    ('Ортопед',    '🦴', 4),
    ('Педиатр',    '🧸', 5),
    ('Гинеколог',  '🌸', 6),
    ('Хирург',     '🔪', 7),
    ('Дерматолог', '🧴', 8),
    ('Офтальмолог','👁️', 9),
    ('ЛОР',        '👂', 10)
) AS v(name, icon, sort_order)
WHERE NOT EXISTS (SELECT 1 FROM crm_doctor_specialties);


-- ===========================================================================
-- RLS / POLICIES (в стиле проекта: anon read+write)
-- ===========================================================================
ALTER TABLE crm_doctor_specialties ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='crm_doctor_specialties' AND policyname='doctor_specialties_read') THEN
        CREATE POLICY doctor_specialties_read ON crm_doctor_specialties FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='crm_doctor_specialties' AND policyname='doctor_specialties_write_anon') THEN
        CREATE POLICY doctor_specialties_write_anon ON crm_doctor_specialties FOR ALL USING (true) WITH CHECK (true);
    END IF;
END $$;

-- crm_doctors RLS-политики уже созданы в sql-sales-plan-payments.sql
-- (crm_doctors_read + crm_doctors_write_anon), повторно не трогаем.

-- ============================================================================
-- END OF MIGRATION
-- ============================================================================
