-- ============================================================================
-- CRM for TP — migration: Sales / Payments / Plan / Profile / Admin stats
-- ============================================================================
-- Назначение: добавить таблицы-кэши и операционные таблицы для новых вкладок
-- (Продажи, Выплаты, План, Профиль ТП, Админ-статистика).
--
-- Принципы:
--   * Все объекты создаются идемпотентно (IF NOT EXISTS).
--   * Frontend читает ТОЛЬКО кэш-таблицы Supabase (crm_onec_sales_cache,
--     crm_docsales_sales_cache, crm_doctors). Реальная синхронизация с 1С (OData)
--     и DocSales выполняется отдельным backend-процессом (service_role / RPC),
--     потому что:
--       - логин/пароль 1С НЕЛЬЗЯ держать во frontend;
--       - OData $filter по Period/Description/Parent_Key в этой базе падает,
--         поэтому выборку нужно делать server-side и складывать в кэш.
--   * Политики RLS сделаны "в стиле проекта": проект сейчас работает через
--     anon-ключ и хранит логин внутри строк (user_login / rep_login). Поэтому
--     по умолчанию разрешаем чтение/запись анонимной роли, чтобы не сломать
--     текущую (небезопасную) модель доступа. Раздел в конце файла содержит
--     более строгий вариант политик — включить после внедрения настоящей авторизации.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- Общий триггер для автоматического обновления updated_at
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;


-- ===========================================================================
-- 1. crm_doctors — справочник врачей (кэш из 1С / DocSales)
-- ===========================================================================
CREATE TABLE IF NOT EXISTS crm_doctors (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doctor_code        TEXT NOT NULL UNIQUE,          -- КодКарты / Code из 1С
    doctor_name        TEXT,                          -- Description
    discount_card_ref  TEXT,                          -- Ref_Key карты в 1С
    discount_card_code TEXT,                          -- КодКарты
    source             TEXT DEFAULT 'onec',           -- 'onec' | 'docsales' | 'manual'
    discount_group     TEXT,                          -- ВидДисконтнойКарты_Key / Parent_Key
    active             BOOLEAN DEFAULT TRUE,
    last_synced_at     TIMESTAMPTZ,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_crm_doctors_code   ON crm_doctors (doctor_code);
CREATE INDEX IF NOT EXISTS idx_crm_doctors_active ON crm_doctors (active);
CREATE INDEX IF NOT EXISTS idx_crm_doctors_source ON crm_doctors (source);

DROP TRIGGER IF EXISTS trg_crm_doctors_updated_at ON crm_doctors;
CREATE TRIGGER trg_crm_doctors_updated_at
    BEFORE UPDATE ON crm_doctors
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ===========================================================================
-- 2. crm_onec_sales_cache — кэш продаж из 1С (AccumulationRegister)
-- ===========================================================================
-- Источник: AccumulationRegister_ПродажиПоДисконтнымКартам_RecordType
-- Поля 1С: Period, Recorder, Active, ДисконтнаяКарта_Key, Сумма, Количество.
-- Заполняется ТОЛЬКО backend-синхронизацией (service_role).
CREATE TABLE IF NOT EXISTS crm_onec_sales_cache (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doctor_code   TEXT NOT NULL,
    period_start  DATE,                  -- начало периода агрегации
    period_end    DATE,                  -- конец периода агрегации
    sale_date     DATE,                  -- дата отдельной записи (если хранится детально)
    recorder      TEXT,                  -- Recorder (ссылка на документ-регистратор)
    amount        NUMERIC(14,2) DEFAULT 0,   -- Сумма (продажи 1С)
    checks_count  INTEGER DEFAULT 0,         -- Количество (чеки 1С = пациенты)
    raw           JSONB,                     -- сырой ответ OData (для отладки)
    synced_at     TIMESTAMPTZ DEFAULT NOW(),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_onec_cache_doctor  ON crm_onec_sales_cache (doctor_code);
CREATE INDEX IF NOT EXISTS idx_onec_cache_period  ON crm_onec_sales_cache (period_start, period_end);
CREATE INDEX IF NOT EXISTS idx_onec_cache_saledate ON crm_onec_sales_cache (sale_date);
-- уникальность строки агрегации по врачу+периоду (для UPSERT из синка)
CREATE UNIQUE INDEX IF NOT EXISTS uq_onec_cache_doc_period
    ON crm_onec_sales_cache (doctor_code, period_start, period_end);

DROP TRIGGER IF EXISTS trg_onec_cache_updated_at ON crm_onec_sales_cache;
CREATE TRIGGER trg_onec_cache_updated_at
    BEFORE UPDATE ON crm_onec_sales_cache
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ===========================================================================
-- 3. crm_docsales_sales_cache — кэш продаж из DocSales
-- ===========================================================================
-- Источник: https://docsales2.vercel.app (Supabase mvjiqysmcclvceswfqwv).
-- Часть таблиц без RLS/auth пустая — заполняется backend-синком (service_role)
-- или остаётся placeholder. Frontend читает только этот кэш.
CREATE TABLE IF NOT EXISTS crm_docsales_sales_cache (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doctor_code   TEXT NOT NULL,
    doctor_name   TEXT,
    period_start  DATE,
    period_end    DATE,
    sale_date     DATE,
    amount        NUMERIC(14,2) DEFAULT 0,   -- продажи DocSales
    checks_count  INTEGER DEFAULT 0,
    external_id   TEXT,                       -- id визита/отчёта в DocSales
    raw           JSONB,
    synced_at     TIMESTAMPTZ DEFAULT NOW(),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_docsales_cache_doctor ON crm_docsales_sales_cache (doctor_code);
CREATE INDEX IF NOT EXISTS idx_docsales_cache_period ON crm_docsales_sales_cache (period_start, period_end);
CREATE UNIQUE INDEX IF NOT EXISTS uq_docsales_cache_doc_period
    ON crm_docsales_sales_cache (doctor_code, period_start, period_end);

DROP TRIGGER IF EXISTS trg_docsales_cache_updated_at ON crm_docsales_sales_cache;
CREATE TRIGGER trg_docsales_cache_updated_at
    BEFORE UPDATE ON crm_docsales_sales_cache
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ===========================================================================
-- 4. crm_doctor_bonus_periods — представление сверки 1С vs DocSales + бонусы
-- ===========================================================================
-- Бизнес-правила:
--   итого к выплате = onec_amount * 0.10 + onec_checks_count * 10
--   bonus_10        = onec_amount * 0.10
--   bonus_patients  = onec_checks_count * 10  (1 чек = 1 пациент = 10)
--   diff_percent    = |onec - docsales| / onec * 100
--   разница > 10 %  => статус сверки 'mismatch' (подсветка во frontend)
CREATE OR REPLACE VIEW crm_doctor_bonus_periods AS
SELECT
    o.doctor_code,
    d.doctor_name,
    o.period_start,
    o.period_end,
    o.amount                                    AS onec_amount,
    o.checks_count                              AS onec_checks_count,
    COALESCE(ds.amount, 0)                       AS docsales_amount,
    COALESCE(ds.checks_count, 0)                 AS docsales_checks_count,
    CASE
        WHEN o.amount IS NULL OR o.amount = 0 THEN NULL
        ELSE ROUND(ABS(o.amount - COALESCE(ds.amount, 0)) / o.amount * 100, 2)
    END                                          AS diff_percent,
    ROUND(o.amount * 0.10, 2)                     AS bonus_10,
    (o.checks_count * 10)                         AS bonus_patients,
    ROUND(o.amount * 0.10 + o.checks_count * 10, 2) AS total_payable,
    CASE
        WHEN o.amount IS NULL OR o.amount = 0 THEN 'no_data'
        WHEN ABS(o.amount - COALESCE(ds.amount, 0)) / o.amount * 100 > 10 THEN 'mismatch'
        ELSE 'matched'
    END                                          AS reconciliation_status
FROM crm_onec_sales_cache o
LEFT JOIN crm_doctors d
    ON d.doctor_code = o.doctor_code
LEFT JOIN crm_docsales_sales_cache ds
    ON ds.doctor_code = o.doctor_code
   AND ds.period_start = o.period_start
   AND ds.period_end   = o.period_end;


-- ===========================================================================
-- 5. crm_doctor_payments — выплаты врачам
-- ===========================================================================
CREATE TABLE IF NOT EXISTS crm_doctor_payments (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doctor_code   TEXT NOT NULL,
    doctor_name   TEXT,
    rep_login     TEXT,                       -- ТП, выполнивший выплату
    period_start  DATE,
    period_end    DATE,
    amount        NUMERIC(14,2) NOT NULL DEFAULT 0,
    payment_date  DATE NOT NULL DEFAULT CURRENT_DATE,
    comment       TEXT,
    created_by    TEXT,                       -- login создателя (admin / TP)
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_payments_doctor   ON crm_doctor_payments (doctor_code);
CREATE INDEX IF NOT EXISTS idx_payments_rep       ON crm_doctor_payments (rep_login);
CREATE INDEX IF NOT EXISTS idx_payments_date       ON crm_doctor_payments (payment_date);
CREATE INDEX IF NOT EXISTS idx_payments_period      ON crm_doctor_payments (period_start, period_end);

DROP TRIGGER IF EXISTS trg_payments_updated_at ON crm_doctor_payments;
CREATE TRIGGER trg_payments_updated_at
    BEFORE UPDATE ON crm_doctor_payments
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ===========================================================================
-- 6. crm_rep_plan_items — план визитов ТП
-- ===========================================================================
-- status: planned | visited | missed | carried_over | cancelled
CREATE TABLE IF NOT EXISTS crm_rep_plan_items (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rep_login              TEXT NOT NULL,
    doctor_code            TEXT,
    doctor_name            TEXT,
    plan_date              DATE NOT NULL,            -- запланированная дата (будний день)
    original_plan_date     DATE,                     -- исходная дата до переноса
    status                 TEXT NOT NULL DEFAULT 'planned',
    planned_payment_amount NUMERIC(14,2) DEFAULT 0,
    actual_payment_amount  NUMERIC(14,2) DEFAULT 0,
    visit_id               TEXT,                     -- id визита из crm_data, закрывшего пункт
    comment                TEXT,
    created_by             TEXT,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_plan_status CHECK (
        status IN ('planned','visited','missed','carried_over','cancelled')
    )
);

CREATE INDEX IF NOT EXISTS idx_plan_rep        ON crm_rep_plan_items (rep_login);
CREATE INDEX IF NOT EXISTS idx_plan_date        ON crm_rep_plan_items (plan_date);
CREATE INDEX IF NOT EXISTS idx_plan_status       ON crm_rep_plan_items (status);
CREATE INDEX IF NOT EXISTS idx_plan_rep_date      ON crm_rep_plan_items (rep_login, plan_date);
CREATE INDEX IF NOT EXISTS idx_plan_doctor         ON crm_rep_plan_items (doctor_code);

DROP TRIGGER IF EXISTS trg_plan_updated_at ON crm_rep_plan_items;
CREATE TRIGGER trg_plan_updated_at
    BEFORE UPDATE ON crm_rep_plan_items
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ===========================================================================
-- 7. crm_rep_points_ledger — журнал баллов ТП
-- ===========================================================================
-- Правила: 1 посещённый врач = +1 балл. Админ может начислить/списать вручную.
-- reason: 'visit' | 'payment_on_time' | 'manual_credit' | 'manual_debit'
CREATE TABLE IF NOT EXISTS crm_rep_points_ledger (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rep_login    TEXT NOT NULL,
    points       INTEGER NOT NULL DEFAULT 0,   -- может быть отрицательным (списание)
    reason       TEXT NOT NULL DEFAULT 'manual_credit',
    ref_type     TEXT,                          -- 'visit' | 'payment' | 'plan' | NULL
    ref_id       TEXT,                          -- id связанной сущности (для идемпотентности)
    comment      TEXT,
    created_by   TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_points_rep    ON crm_rep_points_ledger (rep_login);
CREATE INDEX IF NOT EXISTS idx_points_reason  ON crm_rep_points_ledger (reason);
CREATE INDEX IF NOT EXISTS idx_points_created  ON crm_rep_points_ledger (created_at);
-- защита от двойного начисления за один и тот же визит
CREATE UNIQUE INDEX IF NOT EXISTS uq_points_visit
    ON crm_rep_points_ledger (rep_login, ref_type, ref_id)
    WHERE ref_type IS NOT NULL AND ref_id IS NOT NULL;

DROP TRIGGER IF EXISTS trg_points_updated_at ON crm_rep_points_ledger;
CREATE TRIGGER trg_points_updated_at
    BEFORE UPDATE ON crm_rep_points_ledger
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- ===========================================================================
-- 8. crm_sync_runs — журнал backend-синхронизации 1С / DocSales
-- ===========================================================================
CREATE TABLE IF NOT EXISTS crm_sync_runs (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source        TEXT NOT NULL,           -- all | 1c | docsales
    period_start  DATE,
    period_end    DATE,
    status        TEXT NOT NULL DEFAULT 'partial',
    rows_written  INTEGER NOT NULL DEFAULT 0,
    message       TEXT,
    started_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    finished_at   TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_sync_runs_source ON crm_sync_runs (source);
CREATE INDEX IF NOT EXISTS idx_sync_runs_period ON crm_sync_runs (period_start, period_end);
CREATE INDEX IF NOT EXISTS idx_sync_runs_started ON crm_sync_runs (started_at);


-- ===========================================================================
-- RLS / POLICIES
-- ===========================================================================
-- ВНИМАНИЕ: текущий проект работает через anon-ключ и не использует Supabase Auth.
-- Чтобы не ломать существующее поведение, по умолчанию включаем RLS и даём
-- anon-роли полный доступ к операционным таблицам, а кэш-таблицы 1С/DocSales
-- делаем read-only для anon (писать в них должен только service_role-синк).

ALTER TABLE crm_doctors              ENABLE ROW LEVEL SECURITY;
ALTER TABLE crm_onec_sales_cache     ENABLE ROW LEVEL SECURITY;
ALTER TABLE crm_docsales_sales_cache ENABLE ROW LEVEL SECURITY;
ALTER TABLE crm_doctor_payments      ENABLE ROW LEVEL SECURITY;
ALTER TABLE crm_rep_plan_items       ENABLE ROW LEVEL SECURITY;
ALTER TABLE crm_rep_points_ledger    ENABLE ROW LEVEL SECURITY;
ALTER TABLE crm_sync_runs            ENABLE ROW LEVEL SECURITY;

-- ---- Кэш-таблицы: чтение всем (anon+authenticated), запись — только service_role
DO $$
BEGIN
    -- crm_doctors
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='crm_doctors' AND policyname='crm_doctors_read') THEN
        CREATE POLICY crm_doctors_read ON crm_doctors FOR SELECT USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='crm_doctors' AND policyname='crm_doctors_write_anon') THEN
        -- проект сейчас добавляет врачей из frontend через anon — разрешаем
        CREATE POLICY crm_doctors_write_anon ON crm_doctors FOR ALL USING (true) WITH CHECK (true);
    END IF;

    -- crm_onec_sales_cache (read-only для anon)
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='crm_onec_sales_cache' AND policyname='onec_cache_read') THEN
        CREATE POLICY onec_cache_read ON crm_onec_sales_cache FOR SELECT USING (true);
    END IF;

    -- crm_docsales_sales_cache (read-only для anon)
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='crm_docsales_sales_cache' AND policyname='docsales_cache_read') THEN
        CREATE POLICY docsales_cache_read ON crm_docsales_sales_cache FOR SELECT USING (true);
    END IF;

    -- crm_doctor_payments (full anon — в стиле проекта)
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='crm_doctor_payments' AND policyname='payments_all_anon') THEN
        CREATE POLICY payments_all_anon ON crm_doctor_payments FOR ALL USING (true) WITH CHECK (true);
    END IF;

    -- crm_rep_plan_items (full anon)
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='crm_rep_plan_items' AND policyname='plan_all_anon') THEN
        CREATE POLICY plan_all_anon ON crm_rep_plan_items FOR ALL USING (true) WITH CHECK (true);
    END IF;

    -- crm_rep_points_ledger (full anon)
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='crm_rep_points_ledger' AND policyname='points_all_anon') THEN
        CREATE POLICY points_all_anon ON crm_rep_points_ledger FOR ALL USING (true) WITH CHECK (true);
    END IF;

    -- crm_sync_runs (read-only для anon; пишет backend через service_role)
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='crm_sync_runs' AND policyname='sync_runs_read') THEN
        CREATE POLICY sync_runs_read ON crm_sync_runs FOR SELECT USING (true);
    END IF;
END $$;

-- ---------------------------------------------------------------------------
-- БОЛЕЕ СТРОГИЙ ВАРИАНТ (включить после внедрения Supabase Auth + JWT с ролью)
-- ---------------------------------------------------------------------------
-- Пример: ТП видит только свои планы/выплаты, admin видит всё.
-- Раскомментировать и адаптировать под структуру JWT (auth.jwt() ->> 'login').
--
-- DROP POLICY IF EXISTS plan_all_anon ON crm_rep_plan_items;
-- CREATE POLICY plan_rep_own ON crm_rep_plan_items
--     FOR ALL TO authenticated
--     USING ( rep_login = auth.jwt() ->> 'login'
--             OR (auth.jwt() ->> 'role') = 'admin' )
--     WITH CHECK ( rep_login = auth.jwt() ->> 'login'
--                  OR (auth.jwt() ->> 'role') = 'admin' );
-- ============================================================================
-- END OF MIGRATION
-- ============================================================================
