-- ============================================================================
-- CRM for TP — migration: одобрение устройств (вход только с разрешённых
-- устройств) + принудительный сброс всех сессий
-- ============================================================================
-- Назначение: сайт открывается публично, но ВХОД разрешён только с устройств,
-- которые администратор явно одобрил. Даже при верном логине/пароле вход с
-- неизвестного устройства не выполняется: создаётся заявка на одобрение,
-- админ видит её во вкладке «🔐 Устройства» и жмёт «Одобрить»/«Отклонить».
--
-- Дополнительно: глобальный «рубильник» crm_security_settings.session_version,
-- увеличение которого делает недействительными ВСЕ выданные ранее локальные
-- сессии (кнопка «Выйти из всех аккаунтов» в админ-панели).
--
-- Принципы (в стиле проекта, см. sql-daily-reports.sql):
--   * Все объекты создаются идемпотентно (IF NOT EXISTS / ON CONFLICT / DO $$).
--   * Файл можно запускать повторно — существующие данные НЕ удаляются.
--   * Frontend работает через anon-ключ без Supabase Auth, логин хранится в
--     строках (user_login), поэтому RLS включён, но anon-роли даётся полный
--     доступ — иначе сломается текущая модель. Строгий вариант — в конце файла.
--   * updated_at обслуживается общим триггером set_updated_at().
--
-- ВАЖНО: этот файл НЕ применяется автоматически. Запускать вручную в Supabase
-- SQL Editor. Никаких секретов (service_role, ключи) здесь нет и быть не должно.
--
-- ⚠️ ОГРАНИЧЕНИЕ БЕЗОПАСНОСТИ: это контроль на уровне UI + базы для статического
-- приложения на anon-ключе. Он останавливает обычного пользователя с чужим
-- паролем на чужом устройстве, но НЕ является криптографической привязкой к
-- устройству: у клиента есть anon-ключ, и технически подготовленный человек
-- может обращаться к REST напрямую. Настоящая привязка требует серверной
-- авторизации (Supabase Auth / edge function), проверяющей device_id на
-- сервере при выдаче токена.
-- ============================================================================

-- Общий триггер обновления updated_at (создаётся в других миграциях; дублируем
-- идемпотентно, чтобы файл можно было запускать автономно).
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;


-- ===========================================================================
-- 1. crm_approved_devices — заявки и разрешения на устройства
-- ===========================================================================
-- Одна строка на пару (user_login, device_id).
--   status = 'pending'  — заявка создана при попытке входа, ждёт админа;
--            'approved' — вход с этого устройства разрешён;
--            'rejected' — отклонено/отозвано (запись сохраняем как историю,
--                         повторные попытки входа НЕ переводят её в pending).
--   device_id  — случайный UUID, который фронтенд хранит в localStorage
--                (ключ crm_device_id). Это НЕ отпечаток браузера: очистка
--                localStorage создаст новое устройство → новую заявку.
--   metadata   — безопасные для отображения данные: user agent, платформа,
--                язык, таймзона, разрешение экрана, first_seen/last_seen,
--                requested_login, last_ip (NULL — фронтенд IP не знает).
CREATE TABLE IF NOT EXISTS crm_approved_devices (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_login   TEXT NOT NULL,
    device_id    TEXT NOT NULL,
    status       TEXT NOT NULL DEFAULT 'pending',   -- 'pending' | 'approved' | 'rejected'
    device_name  TEXT,                              -- краткое имя, напр. «Chrome 120 · Windows»
    metadata     JSONB NOT NULL DEFAULT '{}'::jsonb,
    requested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    approved_at  TIMESTAMPTZ,
    approved_by  TEXT,                              -- логин админа
    rejected_at  TIMESTAMPTZ,
    rejected_by  TEXT,
    notes        TEXT,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_crm_approved_device UNIQUE (user_login, device_id)
);

-- Ограничение на допустимые статусы. Добавляем идемпотентно и только если
-- существующие данные ему не противоречат (иначе миграция упала бы).
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'chk_crm_approved_devices_status'
          AND conrelid = 'crm_approved_devices'::regclass
    ) AND NOT EXISTS (
        SELECT 1 FROM crm_approved_devices
        WHERE status NOT IN ('pending', 'approved', 'rejected')
    ) THEN
        ALTER TABLE crm_approved_devices
            ADD CONSTRAINT chk_crm_approved_devices_status
            CHECK (status IN ('pending', 'approved', 'rejected'));
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_crm_approved_devices_login  ON crm_approved_devices (user_login);
CREATE INDEX IF NOT EXISTS idx_crm_approved_devices_device ON crm_approved_devices (device_id);
CREATE INDEX IF NOT EXISTS idx_crm_approved_devices_status ON crm_approved_devices (status);
CREATE INDEX IF NOT EXISTS idx_crm_approved_devices_req_at ON crm_approved_devices (requested_at DESC);

DROP TRIGGER IF EXISTS trg_crm_approved_devices_updated_at ON crm_approved_devices;
CREATE TRIGGER trg_crm_approved_devices_updated_at
    BEFORE UPDATE ON crm_approved_devices
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Автоматически проставляем approved_at / rejected_at при смене статуса, чтобы
-- фронтенду не нужно было помнить об этом (и чтобы данные не разъезжались).
CREATE OR REPLACE FUNCTION crm_devices_stamp_status()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.status = 'approved' AND (OLD.status IS DISTINCT FROM 'approved' OR NEW.approved_at IS NULL) THEN
        NEW.approved_at = COALESCE(NEW.approved_at, NOW());
    END IF;
    IF NEW.status = 'rejected' AND (OLD.status IS DISTINCT FROM 'rejected' OR NEW.rejected_at IS NULL) THEN
        NEW.rejected_at = COALESCE(NEW.rejected_at, NOW());
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_crm_approved_devices_stamp ON crm_approved_devices;
CREATE TRIGGER trg_crm_approved_devices_stamp
    BEFORE UPDATE ON crm_approved_devices
    FOR EACH ROW EXECUTE FUNCTION crm_devices_stamp_status();


-- ===========================================================================
-- 2. crm_login_attempts — журнал попыток входа
-- ===========================================================================
-- Пишется при каждой попытке: успешной и неуспешной. Пароли здесь НЕ хранятся.
--   reason: 'ok' | 'bad_credentials' | 'device_pending' | 'device_rejected'
--           | 'device_unknown' | 'tables_missing'
CREATE TABLE IF NOT EXISTS crm_login_attempts (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_login TEXT,
    device_id  TEXT,
    success    BOOLEAN NOT NULL DEFAULT FALSE,
    reason     TEXT,
    metadata   JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_crm_login_attempts_login   ON crm_login_attempts (user_login);
CREATE INDEX IF NOT EXISTS idx_crm_login_attempts_device  ON crm_login_attempts (device_id);
CREATE INDEX IF NOT EXISTS idx_crm_login_attempts_created ON crm_login_attempts (created_at DESC);


-- ===========================================================================
-- 3. crm_security_settings — глобальные настройки безопасности (одна строка)
-- ===========================================================================
-- session_version  — «эпоха» сессий. Фронтенд сохраняет её в localStorage при
--                    входе и сверяет при загрузке/навигации. Увеличили версию
--                    → все ранее выданные локальные сессии стали недействительны.
-- force_logout_at  — момент принудительного выхода: сессии, выданные раньше,
--                    считаются недействительными (страховка на случай, если
--                    session_version по какой-то причине совпал).
CREATE TABLE IF NOT EXISTS crm_security_settings (
    id              SMALLINT PRIMARY KEY DEFAULT 1,
    session_version INTEGER NOT NULL DEFAULT 1,
    force_logout_at TIMESTAMPTZ,
    updated_by      TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT chk_crm_security_settings_single_row CHECK (id = 1)
);

DROP TRIGGER IF EXISTS trg_crm_security_settings_updated_at ON crm_security_settings;
CREATE TRIGGER trg_crm_security_settings_updated_at
    BEFORE UPDATE ON crm_security_settings
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- Единственная строка. Идемпотентно: повторный запуск НЕ сбрасывает версию.
INSERT INTO crm_security_settings (id, session_version, updated_by)
VALUES (1, 1, 'migration')
ON CONFLICT (id) DO NOTHING;


-- ===========================================================================
-- 4. crm_bump_session_version() — атомарный сброс всех сессий
-- ===========================================================================
-- Вызывается кнопкой «🚪 Выйти из всех аккаунтов» через PostgREST RPC:
--   POST /rest/v1/rpc/crm_bump_session_version  {"p_admin_login": "admin1"}
-- Атомарный инкремент важен: два админа, нажавшие кнопку одновременно, не
-- перезапишут версию друг друга (в отличие от «прочитать и записать» с клиента).
CREATE OR REPLACE FUNCTION crm_bump_session_version(p_admin_login TEXT DEFAULT NULL)
RETURNS TABLE (new_session_version INTEGER, new_force_logout_at TIMESTAMPTZ)
LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO crm_security_settings AS s (id, session_version, force_logout_at, updated_by)
    VALUES (1, 2, NOW(), p_admin_login)
    ON CONFLICT (id) DO UPDATE
        SET session_version = s.session_version + 1,
            force_logout_at = NOW(),
            updated_by      = COALESCE(p_admin_login, s.updated_by)
    RETURNING s.session_version, s.force_logout_at
    INTO new_session_version, new_force_logout_at;

    RETURN NEXT;
END;
$$;

GRANT EXECUTE ON FUNCTION crm_bump_session_version(TEXT) TO anon, authenticated;


-- ===========================================================================
-- RLS / POLICIES (в стиле проекта: anon имеет полный доступ)
-- ===========================================================================
-- ВНИМАНИЕ: проект работает через anon-ключ без Supabase Auth. Чтобы не сломать
-- текущее поведение (фронтенд сам читает/пишет эти таблицы), включаем RLS и
-- даём anon-роли полный доступ. Строгий вариант — в комментарии ниже; включать
-- после внедрения настоящей серверной авторизации.
ALTER TABLE crm_approved_devices  ENABLE ROW LEVEL SECURITY;
ALTER TABLE crm_login_attempts    ENABLE ROW LEVEL SECURITY;
ALTER TABLE crm_security_settings ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='crm_approved_devices' AND policyname='devices_all_anon') THEN
        CREATE POLICY devices_all_anon ON crm_approved_devices FOR ALL USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='crm_login_attempts' AND policyname='login_attempts_all_anon') THEN
        CREATE POLICY login_attempts_all_anon ON crm_login_attempts FOR ALL USING (true) WITH CHECK (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename='crm_security_settings' AND policyname='security_settings_all_anon') THEN
        CREATE POLICY security_settings_all_anon ON crm_security_settings FOR ALL USING (true) WITH CHECK (true);
    END IF;
END $$;


-- ===========================================================================
-- ОПЦИОНАЛЬНО: немедленный выход из всех аккаунтов прямо сейчас
-- ===========================================================================
-- Если нужно выкинуть все текущие сессии сразу, не дожидаясь деплоя и нажатия
-- кнопки в админке — раскомментируйте и выполните одну строку ниже.
-- (То же самое делает кнопка «🚪 Выйти из всех аккаунтов» во вкладке
--  «🔐 Устройства» после деплоя.)
--
-- SELECT * FROM crm_bump_session_version('manual-sql');


-- ===========================================================================
-- ОПЦИОНАЛЬНО: заранее одобрить своё устройство (чтобы не ждать заявку)
-- ===========================================================================
-- device_id можно взять в браузере: DevTools → Console →
--   localStorage.getItem('crm_device_id')
-- (значение появляется после первой загрузки страницы).
--
-- INSERT INTO crm_approved_devices (user_login, device_id, status, device_name, approved_by, approved_at)
-- VALUES ('admin1', 'ВСТАВЬТЕ_DEVICE_ID', 'approved', 'Ноутбук админа', 'manual-sql', NOW())
-- ON CONFLICT (user_login, device_id) DO UPDATE
--     SET status = 'approved', approved_at = NOW(), approved_by = 'manual-sql';


-- ---------------------------------------------------------------------------
-- Более строгий вариант политик (включить ПОСЛЕ внедрения Supabase Auth):
--   пользователь видит только свои устройства, менять статус может только
--   админ. Псевдокод — адаптировать под свою модель ролей:
--
-- DROP POLICY IF EXISTS devices_all_anon ON crm_approved_devices;
-- CREATE POLICY devices_own_read ON crm_approved_devices
--     FOR SELECT USING (user_login = auth.jwt() ->> 'login');
-- CREATE POLICY devices_admin_write ON crm_approved_devices
--     FOR UPDATE USING ((auth.jwt() ->> 'role') = 'admin')
--     WITH CHECK ((auth.jwt() ->> 'role') = 'admin');
-- ---------------------------------------------------------------------------
